version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - dokan_db:/var/lib/postgres
    environment:
      POSTGRES_DB: dokandb
      POSTGRES_USER: dokan_user
      POSTGRES_PASSWORD: password
volumes:
    dokan_db: {}